/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.web;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;

import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.util.HashMap;
import java.util.Map;

import org.eclipse.kura.audit.AuditConstants;
import org.eclipse.kura.audit.AuditContext;
import org.eclipse.kura.web.session.Attributes;
import org.junit.Test;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpSession;

public class ConsoleTest {

    private HttpServletRequest request;
    private AuditContext result;
    private String remoteAddr;
    private Map<String, String> headers;
    private HttpSession session;

    @Test
    public void auditContextUsesRemoteAddrWhenXffHeaderIsPresent() {
        givenHttpRequestWithRemoteAddr("192.168.1.100");
        givenRequestHeader("X-FORWARDED-FOR", "6.6.6.6");

        whenInitAuditContextIsCalled();

        thenAuditIpIs("192.168.1.100");
    }

    @Test
    public void auditContextUsesRemoteAddrWhenXffHeaderIsAbsent() {
        givenHttpRequestWithRemoteAddr("192.168.1.100");

        whenInitAuditContextIsCalled();

        thenAuditIpIs("192.168.1.100");
    }

    @Test
    public void auditContextIncludesForwardedForFieldWhenXffHeaderIsPresent() {
        givenHttpRequestWithRemoteAddr("192.168.1.100");
        givenRequestHeader("X-FORWARDED-FOR", "6.6.6.6");

        whenInitAuditContextIsCalled();

        thenForwardedForFieldIs("6.6.6.6");
    }

    @Test
    public void auditContextOmitsForwardedForFieldWhenXffHeaderIsAbsent() {
        givenHttpRequestWithRemoteAddr("192.168.1.100");

        whenInitAuditContextIsCalled();

        thenForwardedForFieldIsAbsent();
    }

    @Test
    public void auditContextIpIsRemoteAddrEvenWhenSessionHasExistingAuditContext() {
        givenHttpRequestWithRemoteAddr("10.0.0.1");
        givenRequestHeader("X-FORWARDED-FOR", "1.2.3.4");
        givenSessionWithExistingAuditContext("192.168.1.100");

        whenInitAuditContextIsCalled();

        thenAuditIpIs("10.0.0.1");
        thenForwardedForFieldIs("1.2.3.4");
    }

    private void givenHttpRequestWithRemoteAddr(final String remoteAddr) {
        this.remoteAddr = remoteAddr;
        this.headers = new HashMap<>();
        this.session = null;
        this.request = newHttpServletRequest();
    }

    private void givenRequestHeader(final String name, final String value) {
        this.headers.put(name, value);
    }

    private void givenSessionWithExistingAuditContext(final String sessionIp) {
        final Map<String, String> properties = new HashMap<>();
        properties.put(AuditConstants.KEY_IP.getValue(), sessionIp);
        properties.put(AuditConstants.KEY_ENTRY_POINT.getValue(), "WebConsole");
        final AuditContext sessionContext = new AuditContext(properties);

        this.session = newHttpSession(Attributes.AUDIT_CONTEXT.getValue(), sessionContext);
    }

    private void whenInitAuditContextIsCalled() {
        this.result = new Console().initAuditContext(this.request);
    }

    private void thenAuditIpIs(final String expectedIp) {
        assertNotNull(this.result);
        assertEquals(expectedIp, this.result.getProperties().get(AuditConstants.KEY_IP.getValue()));
    }

    private void thenForwardedForFieldIs(final String expectedValue) {
        assertNotNull(this.result);
        assertEquals(expectedValue, this.result.getProperties().get("forwarded.for"));
    }

    private void thenForwardedForFieldIsAbsent() {
        assertNotNull(this.result);
        assertFalse("forwarded.for must not be present when X-Forwarded-For header is absent",
                this.result.getProperties().containsKey("forwarded.for"));
    }

    private HttpServletRequest newHttpServletRequest() {
        return (HttpServletRequest) Proxy.newProxyInstance(HttpServletRequest.class.getClassLoader(),
                new Class<?>[] { HttpServletRequest.class }, (proxy, method, args) -> {
                    final String methodName = method.getName();

                    if ("getRemoteAddr".equals(methodName)) {
                        return this.remoteAddr;
                    } else if ("getHeader".equals(methodName)) {
                        return this.headers.get(args[0]);
                    } else if ("getSession".equals(methodName)) {
                        return this.session;
                    } else if ("getRequestURI".equals(methodName)) {
                        return "/admin/login/password";
                    }

                    return defaultValue(method);
                });
    }

    private HttpSession newHttpSession(final String attributeName, final Object attributeValue) {
        return (HttpSession) Proxy.newProxyInstance(HttpSession.class.getClassLoader(),
                new Class<?>[] { HttpSession.class }, (proxy, method, args) -> {
                    if ("getAttribute".equals(method.getName()) && attributeName.equals(args[0])) {
                        return attributeValue;
                    }

                    return defaultValue(method);
                });
    }

    private Object defaultValue(final Method method) {
        final Class<?> returnType = method.getReturnType();

        if (Boolean.TYPE.equals(returnType)) {
            return false;
        } else if (Byte.TYPE.equals(returnType)) {
            return (byte) 0;
        } else if (Short.TYPE.equals(returnType)) {
            return (short) 0;
        } else if (Integer.TYPE.equals(returnType)) {
            return 0;
        } else if (Long.TYPE.equals(returnType)) {
            return 0L;
        } else if (Float.TYPE.equals(returnType)) {
            return 0F;
        } else if (Double.TYPE.equals(returnType)) {
            return 0D;
        } else if (Character.TYPE.equals(returnType)) {
            return '\0';
        }

        return null;
    }
}
