/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.web.server.net2.configuration;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import static org.mockito.Mockito.mockConstruction;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.Map;

import org.eclipse.kura.configuration.Password;
import org.eclipse.kura.web.server.util.GwtServerUtil;
import org.eclipse.kura.web.shared.model.GwtModemAuthType;
import org.eclipse.kura.web.shared.model.GwtModemInterfaceConfig;
import org.eclipse.kura.web.shared.model.GwtNetIfConfigMode;
import org.eclipse.kura.web.shared.model.GwtNetIfStatus;
import org.eclipse.kura.web.shared.model.GwtNetInterfaceConfig;
import org.eclipse.kura.web.shared.model.GwtNetRouterMode;
import org.eclipse.kura.web.shared.model.GwtWifiNetInterfaceConfig;
import org.junit.jupiter.api.Test;
import org.mockito.MockedConstruction;

public class PreventModemPasswordPlaceholderTest {

    private static final String INTERFACE_NAME = "testInterface";
    private static final String PASSWORD_KEY = "net.interface.testInterface.config.password";

    private GwtModemInterfaceConfig modemConfig;
    private GwtNetInterfaceConfig oldConfig;
    private Map<String, Object> result;

    @Test
    public void placeholderPasswordWithModemOldConfigUsesOldPassword() throws Exception {
        givenModemConfigWithPassword(GwtServerUtil.PASSWORD_PLACEHOLDER);
        givenOldModemConfigWithPassword("oldSecretPassword");

        whenBuildingProperties();

        thenModemPasswordIs("oldSecretPassword");
    }

    @Test
    public void placeholderPasswordWithNonModemOldConfigDoesNotStorePassword() throws Exception {
        givenModemConfigWithPassword(GwtServerUtil.PASSWORD_PLACEHOLDER);
        givenOldWifiConfig();

        whenBuildingProperties();

        thenModemPasswordIsNotStored();
    }

    @Test
    public void realPasswordIsStoredAsIsWithNonModemOldConfig() throws Exception {
        givenModemConfigWithPassword("myRealPassword");
        givenOldWifiConfig();

        whenBuildingProperties();

        thenModemPasswordIs("myRealPassword");
    }

    @Test
    public void realPasswordIsStoredAsIsWithModemOldConfig() throws Exception {
        givenModemConfigWithPassword("myRealPassword");
        givenOldModemConfigWithPassword("oldPassword");

        whenBuildingProperties();

        thenModemPasswordIs("myRealPassword");
    }

    private void givenModemConfigWithPassword(String password) {
        modemConfig = new GwtModemInterfaceConfig();
        modemConfig.setName(INTERFACE_NAME);
        modemConfig.setStatus(GwtNetIfStatus.netIPv4StatusEnabledLAN.name());
        modemConfig.setIpv6Status("netIPv6StatusDisabled");
        modemConfig.setConfigMode(GwtNetIfConfigMode.netIPv4ConfigModeDHCP.name());
        modemConfig.setRouterMode(GwtNetRouterMode.netRouterOff.name());
        modemConfig.setAuthType(GwtModemAuthType.netModemAuthNONE);
        modemConfig.setPassword(password);
        modemConfig.setUsername("testUser");
        modemConfig.setDialString("testDial");
        modemConfig.setResetTimeout(0);
        modemConfig.setHoldoff(0);
        modemConfig.setPppNum(0);
        modemConfig.setMaxFail(0);
        modemConfig.setLcpEchoInterval(0);
        modemConfig.setLcpEchoFailure(0);
    }

    private void givenOldModemConfigWithPassword(String password) {
        GwtModemInterfaceConfig oldModemConfig = new GwtModemInterfaceConfig();
        oldModemConfig.setName(INTERFACE_NAME);
        oldModemConfig.setPassword(password);
        oldConfig = oldModemConfig;
    }

    private void givenOldWifiConfig() {
        GwtWifiNetInterfaceConfig oldWifiConfig = new GwtWifiNetInterfaceConfig();
        oldWifiConfig.setName(INTERFACE_NAME);
        oldConfig = oldWifiConfig;
    }

    private void whenBuildingProperties() throws Exception {
        // Keep the local constructor and isolate only the OSGi configuration adapter.
        try (MockedConstruction<NetworkConfigurationServiceAdapter> adapters = mockConstruction(
                NetworkConfigurationServiceAdapter.class,
                (adapter, context) -> when(adapter.getGwtNetInterfaceConfig(INTERFACE_NAME)).thenReturn(oldConfig))) {
            result = new NetworkConfigurationServicePropertiesBuilder(modemConfig).build();
            assertEquals(1, adapters.constructed().size());
            verify(adapters.constructed().get(0)).getGwtNetInterfaceConfig(INTERFACE_NAME);
        }
    }

    private void thenModemPasswordIs(String expectedPassword) {
        assertTrue(result.containsKey(PASSWORD_KEY), "Modem password should be stored");
        Object passwordObj = result.get(PASSWORD_KEY);
        assertTrue(passwordObj instanceof Password, "Password should be a Password instance");
        assertEquals(expectedPassword, new String(((Password) passwordObj).getPassword()));
    }

    private void thenModemPasswordIsNotStored() {
        assertFalse(result.containsKey(PASSWORD_KEY),
                "Modem password should not be stored when placeholder detected and old config is not modem");
    }
}
