/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.web.server.util;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.fail;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.eclipse.kura.configuration.ComponentConfiguration;
import org.eclipse.kura.configuration.metatype.AD;
import org.eclipse.kura.configuration.metatype.Icon;
import org.eclipse.kura.configuration.metatype.OCD;
import org.eclipse.kura.configuration.metatype.Option;
import org.eclipse.kura.configuration.metatype.Scalar;
import org.eclipse.kura.web.shared.model.GwtConfigParameter;
import org.junit.jupiter.api.Test;

/**
 * Characterizes the contract of {@link GwtComponentServiceInternal#getADProperties(ComponentConfiguration)}:
 * every emitted {@link GwtConfigParameter} must carry the {@code AD}'s default value, matching the sibling
 * converter {@code GwtServerUtil.toGwtConfigParameter}.
 */
public class GwtComponentServiceInternalTest {

    private static final String AD_ID = "+scaleoffset.type";
    private static final String AD_DEFAULT = "DEFINED_BY_VALUE_TYPE";

    private String adDefault;
    private Map<String, Object> configurationProperties;
    private List<GwtConfigParameter> result;

    @Test
    public void adDefaultIsCopiedToEmittedParamWhenPropertyIsAbsent() throws Exception {
        givenAdDefault(AD_DEFAULT);
        givenConfigurationPropertiesWithoutAdId();

        whenGetADPropertiesIsCalled();

        thenParamDefaultEquals(AD_ID, AD_DEFAULT);
        thenParamValueIsNull(AD_ID);
    }

    @Test
    public void adDefaultIsCopiedAlongsideAnExplicitValue() throws Exception {
        givenAdDefault(AD_DEFAULT);
        givenConfigurationPropertyValue(AD_ID, "LONG");

        whenGetADPropertiesIsCalled();

        thenParamValueEquals(AD_ID, "LONG");
        thenParamDefaultEquals(AD_ID, AD_DEFAULT);
    }

    @Test
    public void nullAdDefaultIsNotInvented() throws Exception {
        givenAdDefault(null);
        givenConfigurationPropertiesWithoutAdId();

        whenGetADPropertiesIsCalled();

        thenParamDefaultIsNull(AD_ID);
    }

    /*
     * Given
     */

    private void givenAdDefault(String adDefault) {
        this.adDefault = adDefault;
    }

    private void givenConfigurationPropertiesWithoutAdId() {
        this.configurationProperties = new HashMap<>();
        this.configurationProperties.put("+name", "unrelated");
    }

    private void givenConfigurationPropertyValue(String key, Object value) {
        this.configurationProperties = new HashMap<>();
        this.configurationProperties.put(key, value);
    }

    /*
     * When
     */

    @SuppressWarnings("unchecked")
    private void whenGetADPropertiesIsCalled() throws Exception {
        StubAD ad = new StubAD(AD_ID, this.adDefault);
        StubOCD ocd = new StubOCD(Collections.<AD> singletonList(ad));
        StubComponentConfiguration config = new StubComponentConfiguration(ocd, this.configurationProperties);

        java.lang.reflect.Method method = GwtComponentServiceInternal.class.getDeclaredMethod(
                "getADProperties", ComponentConfiguration.class);
        method.setAccessible(true);
        this.result = (List<GwtConfigParameter>) method.invoke(null, config);
    }

    /*
     * Then
     */

    private void thenParamDefaultEquals(String id, String expected) {
        GwtConfigParameter param = findParam(id);
        assertEquals(expected, param.getDefault(), "default must be copied from the AD's default");
    }

    private void thenParamDefaultIsNull(String id) {
        GwtConfigParameter param = findParam(id);
        assertNull(param.getDefault(), "default must stay null when the AD has no default");
    }

    private void thenParamValueIsNull(String id) {
        GwtConfigParameter param = findParam(id);
        assertNull(param.getValue(), "value must be null when the property is absent from configuration");
    }

    private void thenParamValueEquals(String id, String expected) {
        GwtConfigParameter param = findParam(id);
        assertEquals(expected, param.getValue(), "value must reflect the configured property");
    }

    private GwtConfigParameter findParam(String id) {
        for (GwtConfigParameter param : this.result) {
            if (id.equals(param.getId())) {
                return param;
            }
        }
        fail("no emitted parameter with id [" + id + "]");
        return null;
    }

    /*
     * Stubs
     */

    private static class StubAD implements AD {

        private final String id;
        private final String defaultValue;

        StubAD(String id, String defaultValue) {
            this.id = id;
            this.defaultValue = defaultValue;
        }

        @Override
        public List<Option> getOption() {
            return new ArrayList<>();
        }

        @Override
        public String getName() {
            return "Scale/Offset type";
        }

        @Override
        public String getDescription() {
            return "Scale/Offset type description";
        }

        @Override
        public String getId() {
            return this.id;
        }

        @Override
        public Scalar getType() {
            return Scalar.STRING;
        }

        @Override
        public int getCardinality() {
            return 0;
        }

        @Override
        public String getMin() {
            return null;
        }

        @Override
        public String getMax() {
            return null;
        }

        @Override
        public String getDefault() {
            return this.defaultValue;
        }

        @Override
        public boolean isRequired() {
            return false;
        }
    }

    private static class StubOCD implements OCD {

        private final List<AD> ads;

        StubOCD(List<AD> ads) {
            this.ads = ads;
        }

        @Override
        public List<AD> getAD() {
            return this.ads;
        }

        @Override
        public List<Icon> getIcon() {
            return new ArrayList<>();
        }

        @Override
        public String getName() {
            return "Test OCD";
        }

        @Override
        public String getDescription() {
            return "Test OCD description";
        }

        @Override
        public String getId() {
            return "test.ocd";
        }
    }

    private static class StubComponentConfiguration implements ComponentConfiguration {

        private final OCD ocd;
        private final Map<String, Object> properties;

        StubComponentConfiguration(OCD ocd, Map<String, Object> properties) {
            this.ocd = ocd;
            this.properties = properties;
        }

        @Override
        public String getPid() {
            return "test.pid";
        }

        @Override
        public OCD getDefinition() {
            throw new AssertionError("The local UI must request the localized definition");
        }

        @Override
        public OCD getLocalizedDefinition(String locale) {
            assertEquals(org.eclipse.kura.locale.LocaleContextHolder.getLocale().getLanguage(), locale);
            return this.ocd;
        }

        @Override
        public Map<String, Object> getConfigurationProperties() {
            return this.properties;
        }
    }
}
