/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.web.server.util;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.never;

import org.eclipse.kura.core.configuration.metatype.Tad;
import org.eclipse.kura.core.configuration.metatype.Tscalar;
import org.eclipse.kura.web.shared.model.GwtConfigParameter;
import java.util.Collections;
import java.util.List;
import java.lang.reflect.Method;
import org.eclipse.kura.configuration.ComponentConfiguration;
import org.eclipse.kura.core.configuration.metatype.Tocd;
import org.junit.jupiter.api.Test;

public class GwtServerUtilDefaultValueTest {

    private Tad ad;
    private GwtConfigParameter param;

    @Test
    public void escapedSpacesAreUnescapedForScalar() {
        givenAd(0, "test\\ value");

        whenParameterIsBuilt();

        thenDefaultIs("test value");
    }

    @Test
    public void escapedCommaIsUnescapedForScalar() {
        givenAd(0, "0\\ 0\\ 0\\ ?\\ *\\ *\\ *\\,5");

        whenParameterIsBuilt();

        thenDefaultIs("0 0 0 ? * * *,5");
    }

    @Test
    public void plainDefaultIsUnchanged() {
        givenAd(0, "plain value");

        whenParameterIsBuilt();

        thenDefaultIs("plain value");
    }

    @Test
    public void arrayKeepsSeparatorsAndEscapedCommas() {
        givenAd(3, "a\\,b, c\\ d ,e");

        whenParameterIsBuilt();

        thenDefaultIs("a\\,b,c d,e");
    }

    @Test
    public void nullDefaultStaysNull() {
        givenAd(0, null);

        whenParameterIsBuilt();

        thenDefaultIsNull();
    }

    @Test
    public void emptyDefaultStaysEmpty() {
        givenAd(0, "");

        whenParameterIsBuilt();

        thenDefaultIs("");
    }

    @Test
    @SuppressWarnings("unchecked")
    public void localizedConfigurationKeepsLabelsAndDecodesDefault() throws Exception {
        givenAd(0, "test\\ value");
        this.ad.setName("本地名称");
        this.ad.setDescription("本地说明");
        ComponentConfiguration configuration = mock(
                ComponentConfiguration.class);
        Tocd definition =
                new Tocd();
        definition.addAD(this.ad);
        when(configuration.getLocalizedDefinition("zh")).thenReturn(definition);
        when(configuration.getConfigurationProperties()).thenReturn(Collections.emptyMap());
        Method method = GwtServerUtil.class.getDeclaredMethod("getADProperties",
                ComponentConfiguration.class, String.class);
        method.setAccessible(true);
        List<GwtConfigParameter> parameters =
                (List<GwtConfigParameter>) method.invoke(null, configuration, "zh");
        assertEquals(1, parameters.size());
        assertEquals("test value", parameters.get(0).getDefault());
        assertEquals("本地名称", parameters.get(0).getName());
        assertEquals("本地说明", parameters.get(0).getDescription());
        verify(configuration).getLocalizedDefinition("zh");
        verify(configuration, never()).getDefinition();
    }

    private void givenAd(final int cardinality, final String defaultValue) {
        this.ad = new Tad();
        this.ad.setId("test.property");
        this.ad.setName("Test Property");
        this.ad.setType(Tscalar.STRING);
        this.ad.setCardinality(cardinality);
        this.ad.setDefault(defaultValue);
    }

    private void whenParameterIsBuilt() {
        this.param = GwtServerUtil.toGwtConfigParameter(this.ad, null);
    }

    private void thenDefaultIs(final String expected) {
        assertEquals(expected, this.param.getDefault());
    }

    private void thenDefaultIsNull() {
        assertNull(this.param.getDefault());
    }
}
