/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.web.server.util;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import org.eclipse.kura.configuration.ComponentConfiguration;
import org.eclipse.kura.configuration.ConfigurationService;
import org.eclipse.kura.configuration.Password;
import org.eclipse.kura.core.configuration.ComponentConfigurationImpl;
import org.eclipse.kura.web.shared.model.GwtConfigComponent;
import org.eclipse.kura.web.shared.model.GwtConfigParameter;
import org.eclipse.kura.web.shared.model.GwtConfigParameter.GwtConfigParameterType;
import org.junit.jupiter.api.Test;

public class GwtServerUtilPasswordTest {

    private static final String PASSWORD = "password";
    private static final String PASSWORD_UPPERCASE = "Password";
    private GwtConfigParameter passwordParam;
    private Object currentObjValue;
    private Object result;

    private GwtConfigComponent gwtConfig;
    private ComponentConfigurationImpl currentCC;
    private Map<String, Object> fillResult;

    @Test
    public void placeholderWithNullCurrentValueAndNotRequiredReturnsNull() {
        givenPasswordParam(PASSWORD, false, null);
        givenParamValue(GwtServerUtil.PASSWORD_PLACEHOLDER);
        givenCurrentObjValue(null);

        whenGetUserDefinedObjectIsCalled();

        thenResultIsNull();
    }

    @Test
    public void placeholderWithExistingPasswordCurrentValuePreservesIt() {
        givenPasswordParam(PASSWORD, false, null);
        givenParamValue(GwtServerUtil.PASSWORD_PLACEHOLDER);
        givenCurrentObjValue(new Password("secret"));

        whenGetUserDefinedObjectIsCalled();

        thenResultIsPasswordWithValue("secret");
    }

    @Test
    public void placeholderWithEmptyPasswordCurrentValuePreservesEmptyPassword() {
        givenPasswordParam(PASSWORD, false, null);
        givenParamValue(GwtServerUtil.PASSWORD_PLACEHOLDER);
        givenCurrentObjValue(new Password(""));

        whenGetUserDefinedObjectIsCalled();

        thenResultIsEmptyPassword();
    }

    @Test
    public void placeholderWithNullCurrentValueAndRequiredIgnoresDefaultReturnsNull() {
        givenPasswordParam(PASSWORD, true, "defaultpass");
        givenParamValue(GwtServerUtil.PASSWORD_PLACEHOLDER);
        givenCurrentObjValue(null);

        whenGetUserDefinedObjectIsCalled();

        thenResultIsNull();
    }

    @Test
    public void placeholderWithNullCurrentValueAndRequiredButNoDefaultReturnsNull() {
        givenPasswordParam(PASSWORD, true, null);
        givenParamValue(GwtServerUtil.PASSWORD_PLACEHOLDER);
        givenCurrentObjValue(null);

        whenGetUserDefinedObjectIsCalled();

        thenResultIsNull();
    }

    @Test
    public void nonPlaceholderPasswordValueIsUsedDirectly() {
        givenPasswordParam(PASSWORD, false, null);
        givenParamValue("newpassword");
        givenCurrentObjValue(null);

        whenGetUserDefinedObjectIsCalled();

        thenResultIsPasswordWithValue("newpassword");
    }

    @Test
    public void fillPropertiesUsesNameForPasswordLookup() {
        givenGwtConfigWithPasswordParam(PASSWORD, PASSWORD_UPPERCASE);
        givenCurrentCCWithPassword(PASSWORD_UPPERCASE, new Password("stored"));

        whenFillPropertiesFromConfigurationIsCalled();

        thenFillResultPasswordHasValue(PASSWORD, "stored");
    }

    @Test
    public void fillPropertiesWithNullCurrentCCOmitsPasswordForPlaceholder() {
        givenGwtConfigWithPasswordParam(PASSWORD, PASSWORD_UPPERCASE);

        whenFillPropertiesFromConfigurationWithNullCCIsCalled();

        thenFillResultHasNoPasswordEntry(PASSWORD);
    }

    @Test
    public void fillPropertiesWithExistingConfigurationOmitsAbsentPassword() {
        givenGwtConfigWithPasswordParam(PASSWORD, PASSWORD_UPPERCASE);
        this.currentCC = new ComponentConfigurationImpl("test.pid", null, new HashMap<>());
        whenFillPropertiesFromConfigurationIsCalled();
        thenFillResultHasNoPasswordEntry(PASSWORD);
    }

    @Test
    public void fromGwtComponentOmitsAbsentPasswordAndPreservesMetadata() {
        givenGwtConfigWithPasswordParam(PASSWORD, PASSWORD_UPPERCASE);
        Map<String, Object> properties = new HashMap<>();
        properties.put("kura.service.pid", "service.pid");
        properties.put("kura.service.name", "本地名称");
        properties.put("kura.service.desc", "本地说明");
        this.currentCC = new ComponentConfigurationImpl("test.pid", null, properties);
        Map<String, Object> result = GwtServerUtil.fromGwtConfigComponent(this.gwtConfig, this.currentCC)
                .getConfigurationProperties();
        assertFalse(result.containsKey(PASSWORD));
        assertEquals("service.pid", result.get("kura.service.pid"));
        assertEquals("本地名称", result.get("kura.service.name"));
        assertEquals("本地说明", result.get("kura.service.desc"));
    }

    @Test
    public void componentServiceOmitsAbsentPassword() throws Exception {
        givenGwtConfigWithPasswordParam(PASSWORD, PASSWORD_UPPERCASE);
        ConfigurationService service = mock(ConfigurationService.class);
        when(service.getComponentConfiguration("test.pid"))
                .thenReturn(new ComponentConfigurationImpl("test.pid", null, new HashMap<>()));
        Method method = GwtComponentServiceInternal.class.getDeclaredMethod(
                "getComponentConfiguration", ConfigurationService.class,
                GwtConfigComponent.class);
        method.setAccessible(true);
        ComponentConfiguration result = (ComponentConfiguration) method.invoke(null, service, this.gwtConfig);
        assertFalse(result.getConfigurationProperties().containsKey(PASSWORD));
    }

    @Test
    public void explicitEmptyOrNullPasswordRetainsLocalClearingBehavior() {
        for (String value : new String[] { "", null }) {
            givenGwtConfigWithPasswordParam(PASSWORD, PASSWORD_UPPERCASE);
            this.gwtConfig.getParameters().get(0).setValue(value);
            Map<String, Object> properties = GwtServerUtil.fillPropertiesFromConfiguration(this.gwtConfig, null);
            assertTrue(properties.containsKey(PASSWORD));
            assertNull(properties.get(PASSWORD));
        }
    }

    /*
     * Given
     */

    private void givenPasswordParam(String id, boolean required, String defaultValue) {
        this.passwordParam = new GwtConfigParameter();
        this.passwordParam.setId(id);
        this.passwordParam.setName(id.substring(0, 1).toUpperCase() + id.substring(1));
        this.passwordParam.setType(GwtConfigParameterType.PASSWORD);
        this.passwordParam.setRequired(required);
        this.passwordParam.setCardinality(0);
        if (defaultValue != null) {
            this.passwordParam.setDefault(defaultValue);
        }
    }

    private void givenParamValue(String value) {
        this.passwordParam.setValue(value);
    }

    private void givenCurrentObjValue(Object value) {
        this.currentObjValue = value;
    }

    private void givenGwtConfigWithPasswordParam(String id, String name) {
        this.gwtConfig = new GwtConfigComponent();
        this.gwtConfig.setComponentId("test.pid");

        GwtConfigParameter param = new GwtConfigParameter();
        param.setId(id);
        param.setName(name);
        param.setType(GwtConfigParameterType.PASSWORD);
        param.setRequired(false);
        param.setCardinality(0);
        param.setValue(GwtServerUtil.PASSWORD_PLACEHOLDER);

        this.gwtConfig.setParameters(Arrays.asList(param));
    }

    private void givenCurrentCCWithPassword(String key, Password value) {
        Map<String, Object> props = new HashMap<>();
        props.put(key, value);
        this.currentCC = new ComponentConfigurationImpl("test.pid", null, props);
    }

    /*
     * When
     */

    private void whenGetUserDefinedObjectIsCalled() {
        this.result = GwtServerUtil.getUserDefinedObject(this.passwordParam, this.currentObjValue);
    }

    private void whenFillPropertiesFromConfigurationIsCalled() {
        this.fillResult = GwtServerUtil.fillPropertiesFromConfiguration(this.gwtConfig, this.currentCC);
    }

    private void whenFillPropertiesFromConfigurationWithNullCCIsCalled() {
        this.fillResult = GwtServerUtil.fillPropertiesFromConfiguration(this.gwtConfig, null);
    }

    /*
     * Then
     */

    private void thenResultIsEmptyPassword() {
        assertNotNull(this.result, "result must not be null");
        assertArrayEquals(new char[0], ((Password) this.result).getPassword(), "password must be empty");
    }

    private void thenResultIsNull() {
        assertNull(this.result, "result must be null");
    }

    private void thenResultIsPasswordWithValue(String expected) {
        assertNotNull(this.result, "result must not be null");
        assertArrayEquals(expected.toCharArray(), ((Password) this.result).getPassword(), "password value mismatch");
    }

    private void thenFillResultHasNoPasswordEntry(String key) {
        assertNotNull(this.fillResult, "fill result must not be null");
        assertFalse(this.fillResult.containsKey(key), "password entry must not be present");
    }

    private void thenFillResultPasswordHasValue(String key, String expected) {
        assertNotNull(this.fillResult, "fill result must not be null");
        Object value = this.fillResult.get(key);
        assertNotNull(value, "password entry must be present");
        assertArrayEquals(expected.toCharArray(), ((Password) value).getPassword(), "password value mismatch");
    }
}
